### PR TITLE
Add support for automatically using CircleCI build number as prefix.

### PR DESCRIPTION
**Pull request by alloy**
The variables that get passed to the template aren’t really used atm, but I added this one as well nonetheless for consistency sake.

### CODE REVIEW

**Comment by ashfurrow** [comment]
Gonna merge sans Travis since they appear to be Travis-ing at the moment.

**Comment by ashfurrow** [comment]
I'll push a new version to ruby gems shortly.

**Comment by ashfurrow** [comment]
https://rubygems.org/gems/second_curtain/versions/0.4.0

**Comment by alloy** [comment]
Sweet.

**Pull request merged**
