### PR TITLE
use protocol-independent urls

### PR DESCRIPTION
**Pull request by tiii**
so https:// urls can find jquery

### CODE REVIEW

**Comment by ashfurrow** [comment]
Awesome!

**Comment by ashfurrow** [comment]
Do you need me to tag+push a new gem version to rubygems.org?

**Comment by tiii** [comment]
that would be great! :smile_cat:

**Comment by ashfurrow** [comment]
Done! :coffee:

**Comment by ashfurrow** [comment]
Thanks a lot for your contribution!

**Pull request merged**
